### ISSUE TITLE
Prepare, discuss and finalize usage plans

### ISSUE THREAD

**Issue by ri0t** [c-base/soundlab#11]
_From @ri0t on June 19, 2015 21:19_

This involves responsibilites as well. Thing i personally want to avoid as much as possible:
Crews that have to gather around previous crew's workage. 
The Soundlab should (if possible) be left in a neutral state - if not possible, the crew should be notified and a solution should be discussed and found briefly.

_Copied from original issue: c-base/meta#144_

**Comment by dvzrv** [comment]
dup of #49
