### ISSUE TITLE
Add serious double(?) power cords/circuits to soundlab

### ISSUE THREAD

**Issue by ri0t** [c-base/soundlab#13]
_From @ri0t on June 19, 2015 21:5_

Needs a few separations: 
- [ ] Audio equipment must never meet non-audio equipment where possible - should go on ONE rail that is then to be distributed early on when we have our exclusive 230V rail. (SOON)
- [ ] Light should be adjustable in 2 (max 5) large groups, so no blind tapping and switch research is necessary

_Copied from original issue: c-base/meta#142_

**Comment by dvzrv** [comment]
Dup of #6
