### ISSUE TITLE
Soundlab Wunschliste

### ISSUE THREAD

**Issue by ri0t** [c-base/soundlab#19]
_From @woodworker on June 5, 2014 20:7_

Hier werden dinge genannt die wir fuers soundlab haben wollen

_Copied from original issue: c-base/meta#12_

**Comment by ri0t** [comment]
_From @ij0n on June 7, 2014 11:40_

mit dem ziel eine liste zu haben welches equipment fehlt und beschafft werden muss um die betriebsbereitschaft wieder herzustellen

**Comment by ri0t** [comment]
- Zahlreiche non-high-power LED Spots und ein passendes Montagesystem
- Gardinenführungen (entweder Stahlseil oder Schienen)
- Molton (hinterer Raum einmal an Wand rum)
- Montagematerial für 19" Stangen
- Ein-Zwei Großmembranmikros
- Beamer + Kamera + Licht für Holoprojektionsvortragssystem
- ...

**Comment by ri0t** [comment]
_From @uwekamper on June 8, 2014 15:43_

2-3 Podcast-fähige Mikrofone (günstige Großmembran-Mikros), kann jemand was empfehlen? http://www.thomann.de/de/cat.html?gf=grossmembran_mikrofone&oa=pra

**Comment by ri0t** [comment]
_From @cketti on June 8, 2014 21:12_

/cc @biafra23

**Comment by ri0t** [comment]
_From @uwekamper on June 9, 2014 0:8_

Haben heute ein http://www.akg.com/C1000+S-1039.html?pid=978 gefunden. Das klingt sehr gut.

**Comment by ri0t** [comment]
_From @uwekamper on June 9, 2014 20:16_
- Kleine auf große Klinke und große auf kleine Klinke-Adapter und generell längere Kabel dafür.
- Etwas mit dem man sich selbst Abhören kann beim Podcastern

**Comment by ri0t** [comment]
_From @uwekamper on June 10, 2014 0:24_

http://www.thomann.de/de/behringer_ha400.htm ist beim Sich-selbst-Hören beim Podcasten sehr praktisch.

**Comment by ri0t** [comment]
Ich füge es einfach mal hier hinzu:
19"-Gerätebefestigungsschrauben. Müssen wir doch irgendwo in gröberen Anzahlen haben/herbekommen. Weil nämlich: wer modularsysteme in 19" bauen will braucht sowas, die Stagebox übrigens auch. Desweiteren fände ich einen großen Haufen Große-Klinke-Print-Buchsen total angenehm, dann könnte man nämlich loslegen und 19" Geräte entwerfen. Müssen ja nicht im Soundlab aufgehangen werden,  wir haben noch mehr 19" racks, woanders.

**Comment by woodworker** [comment]
most of this stuff is done
