### ISSUE TITLE
Label printer

### ISSUE THREAD

**Issue by dvzrv** [c-base/soundlab#2]
The coundlab needs its own label printer to cope with the stuff in there properly.
This is most needed for properly assigning cables, etc., but also very useful to mark items of loan, etc.

**Comment by berlincount** [comment]
There is a label printer on the bridge, this could be put into (better) general use.

**Comment by dvzrv** [comment]
When/how can we make use of it? Are only board members able to get it (or any key member)?
I'd like to label all the inventory, so everyone knows what belongs to whom, nothing useful gets thrown away.
In reverse, this also means: Everyone, label your stuff (with the label maker or with tape and a pen, or whatever).
Soundlab is too small to hord useless stuff (this counts for the station, too).

**Comment by dvzrv** [comment]
The c-lab also has a label printer that we can/should use.

**Comment by dvzrv** [comment]
Duplicate of: #46
