### ISSUE TITLE
Carpet

### ISSUE THREAD

**Issue by dvzrv** [c-base/soundlab#3]
The coundlab needs a carpet, as the floor is not properly sealed, and will generate a lot of dust, which is unhealthy for humanoids and bad for equipment alike.
Furthermore a continous carpet will improve the dryness (soundwise) of the room!

**Comment by ri0t** [comment]
We have budget for 144 EUR planned for this.

**Comment by dvzrv** [comment]
cilli suggested going to a "Restposten" space to buy a suitable carpet for minimum amount of money.
I kinda like that idea actually. We just need to get the proper measurements, rent a car or something to get to such a space and get the carpet.
This way we will be able to get a room filling carpet! weee!

**Comment by dvzrv** [comment]
Dump your pattern here for the contest! The best will be layed out in red+black in the soundlab!

**Comment by dvzrv** [comment]
https://wiki.c-base.org/dokuwiki/_detail/soundlab:soundlab_plan.png?id=soundlab%3Arooms
We need: 5,26m x 3,33m (17,52m²) for the recording room.
40cm x 40cm tiles: 14 x 9 tiles (126 tiles) ~ 120€

We need 5,26m x 4,03m (21,20m²) for the studio room (optional).
40cm x 40cm tiles: 14 x 11 (154 tiles) ~ 130€

**Comment by ri0t** [comment]
In theory, we picked up some carpet from 34c3. But i suspect it hasn't been delivered. Hm. Hunting for it.
