### ISSUE TITLE
Soundlab calendar

### ISSUE THREAD

**Issue by woodworker** [c-base/soundlab#30]
We need a calendar where all members can add "reservations"

**Comment by ri0t** [comment]
Working on it.

**Comment by ri0t** [comment]
90% done, i'm just fighting a few last bugs. It'll also allow reservation of equipment and inventory of such ;)

**Comment by ri0t** [comment]
http://imgur.com/a/oPuaL

**Comment by ri0t** [comment]
this is available on https://hfos.cbrp3.c-base.org
The upgrade so it supports LDAP is incoming, also a few other features that make this tool more useful (better feedback, partial reservations, etc..)
