### ISSUE TITLE
Ventilation system

### ISSUE THREAD

**Issue by dvzrv** [c-base/soundlab#4]
The coundlab needs a ventilation system to efficiently and substantially lower the humidity in the two rooms!

**Comment by berlincount** [comment]
Please be aware that the low temperature actually in the rooms actually means that any (warmer) air ventilated into these rooms will ensure condensation, i.e. MORE humidity in the rooms!

**Comment by dvzrv** [comment]
The ventilation is actually meant to suck air out of the room, not necessarily blow it into the room.
At the moment the only way to keep the room in good state is to regularly open all doors and let the weltenbaulab smell in ;-)
That smoke is not good for any of the equipment.
Then again... neither is the dust in there ;-)

**Comment by dvzrv** [comment]
A general ventilation system for upstairs is in the (monetary) making. If and when the soundlab can be hooked up to it is not yet clear.

For now regularly opening the doors and keeping track of humidity and temperature in the rooms is a soundlab crew task (part of the regular maintenance)!
