### ISSUE TITLE
updates on soundlab computer (sudoer help needed!)

### ISSUE THREAD

**Issue by TeddyKopernikus** [c-base/soundlab#66]
- regular system updates (if not happening automaticall)
- update for bitwig (installed: 1.3.12 current: 1.3.15 offered at prog start)
- installation of the following programs: musescore, lilypond, rosegarden, ardour, tuxguitar e.g. via terminal by calling "sudo apt-get install musescore lilypond rosegarden ardour tuxguitar"

**Comment by ri0t** [comment]
Done - lilypond is currently broken due to libguile
